package com.wolcano.musicplayer.music.mvp.db;



import com.wolcano.musicplayer.music.mvp.models.Song;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class GreenDaoSession extends AbstractDaoSession {
    private final AppDao appDao;
    private final DaoConfig daoConfig;


    public GreenDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoConfig = daoConfigMap.get(AppDao.class).clone();
        daoConfig.initIdentityScope(type);

        appDao = new AppDao(daoConfig, this);

        registerDao(Song.class, appDao);
    }
    
    public void clear() {
        daoConfig.clearIdentityScope();
    }

    public AppDao getAppDao() {
        return appDao;
    }

}
